# Generated by Django 6.0.5 on 2026-05-19 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournament", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_mvp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MVP predicho"
                    ),
                ),
                (
                    "predicted_top_scorer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pichichi predicho"
                    ),
                ),
                (
                    "predicted_best_goalkeeper",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zamora predicho"
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="participants",
                        to="tournament.nationalteam",
                        verbose_name="Selecciones elegidas",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "ordering": ["-score_logs__points_earned"],
            },
        ),
        migrations.CreateModel(
            name="ScoreLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_earned",
                    models.SmallIntegerField(verbose_name="Puntos obtenidos"),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Descripción legible del motivo: 'Victoria vs Francia', 'Clasificado a cuartos'...",
                        max_length=200,
                        verbose_name="Motivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nulo para puntos de premios individuales o avance de fase",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_logs",
                        to="tournament.match",
                        verbose_name="Partido",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_logs",
                        to="pool.participant",
                        verbose_name="Participante",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_logs",
                        to="tournament.nationalteam",
                        verbose_name="Selección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de puntuación",
                "verbose_name_plural": "Registros de puntuación",
                "ordering": ["-created_at"],
            },
        ),
    ]
