# Generated by Django 6.0.5 on 2026-06-07

from django.db import migrations, models


def forwards(apps, schema_editor):
    ScoreLog = apps.get_model("pool", "ScoreLog")

    phase_by_label = {
        "Dieciseisavos de final": "R32",
        "Octavos de final": "R16",
        "Cuartos de final": "QF",
        "Semifinales": "SF",
        "Tercer puesto": "3PL",
        "Final": "FIN",
    }

    for score_log in ScoreLog.objects.all().iterator():
        if score_log.reason_code:
            continue

        reason = score_log.reason or ""
        reason_code = ""
        reason_context = {}

        if reason.startswith("Victoria vs "):
            reason_code = "match_win"
            reason_context = {"rival": reason.removeprefix("Victoria vs ").strip()}
        elif reason.startswith("Empate vs "):
            reason_code = "match_draw"
            reason_context = {"rival": reason.removeprefix("Empate vs ").strip()}
        elif reason.startswith("Derrota vs "):
            reason_code = "match_loss"
            reason_context = {"rival": reason.removeprefix("Derrota vs ").strip()}
        elif reason.startswith("Clasificado desde grupo "):
            reason_code = "group_advance"
            reason_context = {
                "group": reason.removeprefix("Clasificado desde grupo ").strip()
            }
        elif reason.startswith("1º de grupo "):
            reason_code = "group_first"
            reason_context = {"group": reason.removeprefix("1º de grupo ").strip()}
        elif reason.startswith("Clasificado a "):
            phase_label = reason.removeprefix("Clasificado a ").strip()
            reason_code = "advance_phase"
            reason_context = {"phase": phase_by_label.get(phase_label, phase_label)}
        elif reason == "3er puesto":
            reason_code = "third_place"
        elif reason == "¡Campeón del Mundial!":
            reason_code = "champion"
        elif reason == "Acertó el MVP del torneo":
            reason_code = "mvp"
        elif reason == "Acertó el Pichichi":
            reason_code = "top_scorer"
        elif reason == "Acertó el Zamora":
            reason_code = "best_goalkeeper"

        if reason_code:
            score_log.reason_code = reason_code
            score_log.reason_context = reason_context
            score_log.save(update_fields=["reason_code", "reason_context"])


def backwards(apps, schema_editor):
    ScoreLog = apps.get_model("pool", "ScoreLog")
    for score_log in ScoreLog.objects.all().iterator():
        score_log.reason_code = ""
        score_log.reason_context = {}
        score_log.save(update_fields=["reason_code", "reason_context"])


class Migration(migrations.Migration):
    dependencies = [
        ("pool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorelog",
            name="reason_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Identificador estable para traducir el motivo.",
                max_length=50,
                verbose_name="Código del motivo",
            ),
        ),
        migrations.AddField(
            model_name="scorelog",
            name="reason_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Datos auxiliares para construir el motivo traducido.",
                verbose_name="Contexto del motivo",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
