# Generated by Django 6.0.5 on 2026-05-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NationalTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(
                        help_text="Código ISO de 3 letras, p.ej. ESP, ARG",
                        max_length=3,
                        unique=True,
                        verbose_name="Código FIFA",
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True,
                        help_text="Emoji de la bandera, p.ej. 🇪🇸",
                        max_length=10,
                        verbose_name="Emoji bandera",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        help_text="Letra del grupo (A-L)",
                        max_length=1,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        help_text="Coste en monedas para elegir esta selección",
                        verbose_name="Precio (monedas)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selección nacional",
                "verbose_name_plural": "Selecciones nacionales",
                "ordering": ["group", "name"],
            },
        ),
        migrations.CreateModel(
            name="TournamentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget",
                    models.PositiveSmallIntegerField(
                        default=220,
                        verbose_name="Presupuesto por participante (monedas)",
                    ),
                ),
                (
                    "real_mvp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MVP real del torneo"
                    ),
                ),
                (
                    "real_top_scorer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pichichi real"
                    ),
                ),
                (
                    "real_best_goalkeeper",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Zamora real (mejor portero)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del torneo",
                "verbose_name_plural": "Configuración del torneo",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("GRP", "Fase de grupos"),
                            ("R16", "Octavos de final"),
                            ("QF", "Cuartos de final"),
                            ("SF", "Semifinales"),
                            ("FIN", "Final"),
                        ],
                        max_length=3,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Solo para partidos de fase de grupos",
                        max_length=1,
                        verbose_name="Grupo",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Fecha y hora")),
                (
                    "home_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Goles local"
                    ),
                ),
                (
                    "away_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Goles visitante"
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Finalizado"),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="tournament.nationalteam",
                        verbose_name="Visitante",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="tournament.nationalteam",
                        verbose_name="Local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
