# Generated by Django 6.0.5 on 2026-05-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_label",
            field=models.CharField(
                blank=True,
                help_text="Descripción del cruce en fases eliminatorias, p.ej. '1A vs 2B'",
                max_length=60,
                verbose_name="Etiqueta del cruce",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_matches",
                to="tournament.nationalteam",
                verbose_name="Visitante",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_matches",
                to="tournament.nationalteam",
                verbose_name="Local",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="phase",
            field=models.CharField(
                choices=[
                    ("GRP", "Fase de grupos"),
                    ("R16", "Dieciseisavos de final"),
                    ("QF", "Cuartos de final"),
                    ("SF", "Semifinales"),
                    ("3PL", "Tercer puesto"),
                    ("FIN", "Final"),
                ],
                max_length=3,
                verbose_name="Fase",
            ),
        ),
    ]
