# Generated by Django 6.0.5 on 2026-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_nullable_teams_match_label_third_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="phase",
            field=models.CharField(
                choices=[
                    ("GRP", "Fase de grupos"),
                    ("R32", "Dieciseisavos de final"),
                    ("R16", "Octavos de final"),
                    ("QF", "Cuartos de final"),
                    ("SF", "Semifinales"),
                    ("3PL", "Tercer puesto"),
                    ("FIN", "Final"),
                ],
                max_length=3,
                verbose_name="Fase",
            ),
        ),
    ]
