# Generated by Django 6.0.5 on 2026-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0003_add_round_of_32_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="venue",
            field=models.CharField(blank=True, max_length=100, verbose_name="Sede"),
        ),
    ]
