# Generated by Django 6.0.5 on 2026-05-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0004_add_venue_to_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="next_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feeder_matches",
                to="tournament.match",
                verbose_name="Siguiente partido del bracket",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="next_match_slot",
            field=models.CharField(
                blank=True,
                choices=[("home", "Local"), ("away", "Visitante")],
                max_length=4,
                default="",
                verbose_name="Slot en el siguiente partido",
            ),
        ),
    ]
