# Generated by Django 6.0.5 on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0005_add_next_match_to_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="penalties_winner",
            field=models.CharField(
                blank=True,
                choices=[("home", "Local"), ("away", "Visitante")],
                default="",
                help_text="Solo para eliminatorias cuando hay empate en el marcador",
                max_length=4,
                verbose_name="Ganador por penaltis",
            ),
        ),
    ]
