# Generated by Django 6.0.5 on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0006_add_penalties_winner_to_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="decided_in_90",
            field=models.BooleanField(
                default=True,
                help_text="Solo para eliminatorias: si es False, victoria por prórroga o penaltis",
                verbose_name="Resuelto en 90 minutos",
            ),
        ),
    ]
